# Generated by Django 3.2.8 on 2021-10-25 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20211025_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='event_date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
