# Generated by Django 3.2.8 on 2021-10-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_event_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='event_date_added',
        ),
    ]
