# Generated by Django 3.2.8 on 2021-10-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('university_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('admission_number', models.CharField(max_length=100)),
                ('graduation_year', models.DateField()),
                ('member_image', models.ImageField(upload_to='accounts/images/')),
            ],
        ),
    ]
