# Generated by Django 3.2.8 on 2021-11-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_image',
        ),
    ]
