# Generated by Django 3.2.8 on 2021-11-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211127_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='graduation_year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
