# Generated by Django 3.2.8 on 2021-11-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211127_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_image',
            field=models.ImageField(null=True, upload_to='accounts/images/'),
        ),
    ]
