# Generated by Django 3.2.8 on 2021-11-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_image',
            field=models.ImageField(default='', upload_to='accounts/images/'),
        ),
    ]
